/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'BhavaMada' at '25/10/16 13:20' with Gradle 2.13
 *
 * @author BhavaMada, @date 25/10/16 13:20
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
